### ISSUE TITLE
FileLock::lock asks for an str instead of OsStr or Path

### ISSUE THREAD

**Issue by Diegovsky** [alfiedotwtf/file-lock#1]
To deal with OS paths, the standard library uses `Path` (and friends) because it abstracts [encoding incompatibilities](https://doc.rust-lang.org/std/path/index.html) with `str`. As an example, [File::open](https://doc.rust-lang.org/std/fs/struct.File.html#method.open) takes `impl AsRef<Path>`. I think `FileLock::lock` should follow the same pattern to be consistent with std but also because `OsStr` can be passed to the OS while `str` might not.

**Comment by alfiedotwtf** [comment]
Thanks for the feedback. Yep, you're right.

If you want to submit a PR, feel free and I'll be more than happy to merge. Otherwise, I should get some time in the next few days.

Thank again!

**Comment by Diegovsky** [comment]
Thanks for the quick response! I'll make a PR soon :)

**Comment by michidk** [comment]
I just noticed the same and created a PR (https://github.com/alfiedotwtf/file-lock/pull/2)!

**Comment by alfiedotwtf** [comment]
Sorry for the long delay.

Thanks again for this one. I keep forgetting about `OsStr`!
