### ISSUE TITLE
RAII?

### ISSUE THREAD

**Issue by untitaker** [alfiedotwtf/file-lock#10]
I'd like `lock()` to be automatically called when creating the object with `Lock::new`.

The reason for this that I feel incredibly uneasy when I get a lock object from another API: Is the lock already acquired? Am *I* expected to call `lock()`? Even if there'd be a way to tell whether a lock is already acquired, I'd still feel uneasy, since I'd have to check for this whenever I recieve a lock from another API.

**Comment by Byron** [comment]
I totally see the point you are making, thanks for posting it here !

In Rust, one would probably solve this by using *Guards*, and semantics very similar to what is shown by the `Mutex` type.

Right now, this crate is only fit for internal use, and passing along `Lock` instances shouldn't be done for safety reasons.

Would you like to step in and implement something like a `mutexlike::Lock` to alleviate the issue ? I don't need it myself and thus wouldn't do so anytime soon.

**Comment by untitaker** [comment]
The mutex type differs because when two threads acquire the lock, they use the same mutex object. In the case of filelocks, threads can just create their own objects to acquire the same lock.

I don't see why an API on top of this would be better. Together with #9 one could provide this convenience interface on the same struct without duplicated effort across lock types.

I'll whip up a PR to show what I mean.

On 16 October 2015 09:27:37 CEST, Sebastian Thiel <notifications@github.com> wrote:
>I totally see the point you are making, thanks for posting it here !
>
>In Rust, one would probably solve this by using *Guards*, and semantics
>very similar to what is shown by the `Mutex` type.
>
>Right now, this crate is only fit for internal use, and passing along
>`Lock` instances shouldn't be done for safety reasons.
>
>Would you like to step in and implement something like a
>`mutexlike::Lock` to alleviate the issue ? I don't need it myself and
>thus wouldn't do so anytime soon.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/alfiedotwtf/file-lock/issues/10#issuecomment-148636571

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Hmm. I wonder if that assumption was even right:

>In the case of filelocks, threads can just create their own objects to acquire the same lock.

If I look at the internals of `filename`, I'm really not sure anymore...

**Comment by Byron** [comment]
Two threads will be able to 'acquire' the same lock without waiting, which can be a problem. Multiple processes, however, cannot.
This is tested and verified in the test-suite, which launches multiple processes as well.

I am looking forward to what you come up with.

**Comment by untitaker** [comment]
Is that true for both lock types?

**Comment by untitaker** [comment]
Hang on, I don't get it. Why would two threads have to share the lock object, but two processes not?

**Comment by Byron** [comment]
It's true for both lock-types, they both use the same mechanism (i.e. FileLock API).
It seems that the filesystem API will only protect multiple processes from accessing the same file resource, it doesn't apply to threads in the same process though.
This is fine for the use-case I am seeing.

**Comment by untitaker** [comment]
So what you're saying is that file locks can't be used to synchronize threads at all?

This test passes for me:


    #[test]
    fn foo() {
        let mut one = FileLock::new(path::Path::new("lol").to_owned(), Mode::Write);
        one.lock().unwrap();
        one.lock().unwrap();
    }

**Comment by Byron** [comment]
I don't think it's viable for usage with multiple threads.

**Comment by untitaker** [comment]
Ah, I see. In that case I fear that I will have to find something else :(

Would you know of a RwLock-ish thing that avoids storing all locks in RAM?

**Comment by Byron** [comment]
On linux file-systems (non-network), you can atomically (supposedly) atomically create a file with `O_CREAT|O_EXCL` , together with permissions to prevent writing by others. That way, no two threads or processes can use the same resource, but failing to remove the file usually prevents anyone to use it in future too (see `git gc` failing forever if you kill its previous invocation).

Do you think the issue can be closed ?

**Comment by untitaker** [comment]
Ah yeah, but I'd have to impl my own locking crate on top of that.

I think the RAII idea is a good one but I don't really have the time to work on it (sorry :( ), so it's your call.

**Comment by Byron** [comment]
I think RAII is valid, but isn't anything I'd need right now.
In case that changes, I will open a new issue.
